# Generated by Django 5.1 on 2024-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codesubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=15)),
                ('code', models.TextField()),
                ('input_data', models.TextField(blank='True', null='True')),
                ('output_data', models.TextField(blank='True', null='True')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
