# Generated by Django 5.1 on 2024-08-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='output_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
