# Generated by Django 5.1 on 2024-08-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_list',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=255)),
                ('question_statement', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('mediam', 'Mediam'), ('hard', 'Hard')], default='Easy', max_length=6)),
            ],
        ),
    ]
