# Generated by Django 5.1 on 2024-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_code_check_code_record_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('mediam', 'Mediam'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
    ]
