# Generated by Django 5.1 on 2024-08-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_register_delete_tuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='name',
            new_name='username',
        ),
    ]
