# Generated by Django 5.1 on 2024-08-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_user_register_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
