# Generated by Django 5.1 on 2024-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
